### ISSUE TITLE
QX, Quantum Inspire missing from Simulators list

### ISSUE THREAD

**Issue by amitabhyadav** [qosf/qosf.org#18]
You can add Quantum Inspire and QX Simulator developed from QuTech, Delft to the list. Both are released and publicly accessible at: 
http://quantum-studio.net/
https://www.quantum-inspire.com/

**Comment by markf94** [comment]
Hi @amitabhyadav! Thanks for getting involved. May I ask you to open a MR adding Quantum Inspire and QX Simulator to the official list of quantum open source projects? (https://github.com/qosf/awesome-quantum-software) The list on the QOSF website is actually auto-generated from that list.

That would be a great help!

**Comment by markf94** [comment]
Closing this since this concerns the other repo: https://github.com/qosf/awesome-quantum-software
