### ISSUE TITLE
Automate the list of contributors

### ISSUE THREAD

**Issue by markf94** [qosf/qosf.org#28]
Updating the list of contributors in `team.md` is currently done manually. This should be automated with a script that pulls the authors of issues and MRs on all `qosf` repos, sorts them alphabetically and adds the corresponding HTML snippet to `team.md`

**Comment by manulpatel** [comment]
Hi @markf94! I would like to implement the automation for list of contributors. To get started, do you recommend any specific tool or library to be used in our case for the script?

**Comment by MZuhairKhan** [comment]
Hey @markf94! I'd love to tackle this problem. Could you assign it to me?

**Comment by MZuhairKhan** [comment]
I have submitted a pull request. Let me know if anything needs to be changed!

**Comment by victor-onofre** [comment]
Hi @MZuhairKhan, this looks great! I have posted an update of the foundation here #89. Please check it to clarify any questions about the status of the QOSF.  

I will check the PR later today or on Monday. 

Thanks!

**Comment by MZuhairKhan** [comment]
Hey @victor-onofre! Any updates on this?

**Comment by victor-onofre** [comment]
Hi @MZuhairKhan! Sorry for the delay. I have been busy with work. I took a quick look, and it seems good! But right now, we are having some issues with the website. @MaldoAlberto is working on fixing the problem. He is going to take care of the review of this issue. 

Thanks for your help!

**Comment by MaldoAlberto** [comment]
@MZuhairKhan solved this issue

**Comment by MZuhairKhan** [comment]
@MaldoAlberto alright thanks! Do I need to do anything for the bounty?
