### ISSUE TITLE
Twitter account suspended

### ISSUE THREAD

**Issue by alexandrevicenzi** [qosf/qosf.org#4]
As the title.

https://www.twitter.com/qosfoundation

**Comment by markf94** [comment]
yeah thanks for pointing this out! The problem was that we did create the account before being able to receive confirmation emails. I'm on it!

**Comment by amirebrahimi** [comment]
Looks like this can be closed, no? I was able to follow the account.

**Comment by markf94** [comment]
Thanks @amirebrahimi for helping us clean up :)
