### ISSUE TITLE
Update on 'IBM Q Full User Guide' learning link

### ISSUE THREAD

**Issue by des137** [qosf/qosf.org#43]
The link for 'IBM Q Full User Guide' under Learning Resources (in _learn_quantum.md_) does not work. I did not open a PR because I was not sure which of the following links did the developers had in mind: 
1. https://quantum-computing.ibm.com/jupyter
2. https://quantum-computing.ibm.com/docs/

**Comment by markf94** [comment]
Great observation @des137! Will try to update that soon!
