### ISSUE TITLE
Update the QOSF website

### ISSUE THREAD

**Issue by MaldoAlberto** [qosf/qosf.org#95]
We need to update the website with new information. The reason is to explain in detail the processes done in QOSF, including the monthly challenge, the mentoring program, and the courses on YouTube.

We need to generate a new format to present the mentors as mentees who have participated and participated before. We also need to generate new pages and propose what we can add to update the website following the QOSF style and color palette. 

We have got some updates to make to the website!   We should generate something more animated to present mentors. For example, we should create a carousel with mentors' photos, names, and origins. We should also create a carousel for mentees.

For the cohorts, we need to create new pages and perform the same process as above, but with updated cohort numbers. Similarly, we should create new pages for the monthly challenge and link the responses of those who have completed it month by month on the website.

Finally, we link the responses of those who have completed a monthly challenge month by month at the website.

Necesitamos actualizar la página web con nueva información. El motivo es explicar en detalle los procesos que se llevan a cabo en QOSF, incluido el reto mensual, el programa de mentores y los cursos en YouTube.

Necesitamos generar un nuevo formato para presentar a los mentores como mentees que han participado y participado anteriormente. También necesitamos generar nuevas páginas y proponer qué podemos añadir para actualizar el sitio web siguiendo el estilo y la paleta de colores de QOSF. 

¡Tenemos algunas actualizaciones que hacer en el sitio web!   Deberíamos generar algo más animado para presentar a los mentores. Por ejemplo, deberíamos crear un carrusel con las fotos, los nombres y los orígenes de los mentores. También deberíamos crear un carrusel para los alumnos.

Para las cohortes, debemos crear nuevas páginas y realizar el mismo proceso anterior, pero con los números de cohorte actualizados. Del mismo modo, debemos crear nuevas páginas para el reto mensual y enlazar las respuestas de quienes lo han completado mes a mes en el sitio web.

Por último, enlazamos las respuestas de quienes han completado el reto mensual mes a mes en el sitio web.

**Comment by Qubit1718** [comment]
Hi Alberto, 
I would like to work on updating the QOSF website and making the required changes. Please let me know what would be the starting point to go about solving this?

**Comment by jalaln06** [comment]
Hi everyone! I'd also like to work on updating QOSF website if needed

**Comment by s-peryt** [comment]
Idea is good, but I'd suggest starting with basics - i.e. updating website to actually provide useful information (see my issue #89 ). I don't think adding new features is something that should be first priority.

**Comment by victor-onofre** [comment]
Hi @s-peryt, @jalaln06, @Qubit1718! 

I have added an update in issue #89. Please check it to clarify some doubts.   

Thanks!
